/* Description: Getting the products and update the salesprice in this apex class
* Author: Nagarjuna Reddy
* Created Date: 08/12/2023
*/
public class ProductConstants {
    /**
     * The constant string representing a success message.
     * Use this constant when an operation is successful.
     */
	// declare the variables for success and failed strings
    public static final String SUCCESS_MESSAGE = 'success';
    
    /**
     * The constant string representing a failed message.
     * Use this constant when an operation encounters an error or failure.
     */
    
    public static final String FAILED_MESSAGE = 'failed';
}